//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class LuaAddressablesWrap
{
	public static void Register(LuaState L)
	{
		L.BeginStaticLibs("LuaAddressables");
		L.RegFunction("LoadAssetAsync", LoadAssetAsync);
		L.RegFunction("GetDownloadSizeAsync", GetDownloadSizeAsync);
		L.EndStaticLibs();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int LoadAssetAsync(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			object arg0 = ToLua.ToVarObject(L, 1);
			UnityEngine.ResourceManagement.AsyncOperations.AsyncOperationHandle<object> o = LuaAddressables.LoadAssetAsync(arg0);
			ToLua.PushValue(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetDownloadSizeAsync(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			object arg0 = ToLua.ToVarObject(L, 1);
			UnityEngine.ResourceManagement.AsyncOperations.AsyncOperationHandle<long> o = LuaAddressables.GetDownloadSizeAsync(arg0);
			ToLua.PushValue(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

