//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class LuaCollisionListenerWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(LuaCollisionListener), typeof(UnityEngine.MonoBehaviour));
		L.RegFunction("AddListener", AddListener);
		L.RegFunction("RemoveListener", RemoveListener);
		L.RegFunction("RemoveAllListeners", RemoveAllListeners);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int AddListener(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			LuaCollisionListener obj = (LuaCollisionListener)ToLua.CheckObject<LuaCollisionListener>(L, 1);
			System.Action<UnityEngine.Collision> arg0 = (System.Action<UnityEngine.Collision>)ToLua.CheckDelegate<System.Action<UnityEngine.Collision>>(L, 2);
			obj.AddListener(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int RemoveListener(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			LuaCollisionListener obj = (LuaCollisionListener)ToLua.CheckObject<LuaCollisionListener>(L, 1);
			System.Action<UnityEngine.Collision> arg0 = (System.Action<UnityEngine.Collision>)ToLua.CheckDelegate<System.Action<UnityEngine.Collision>>(L, 2);
			obj.RemoveListener(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int RemoveAllListeners(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			LuaCollisionListener obj = (LuaCollisionListener)ToLua.CheckObject<LuaCollisionListener>(L, 1);
			obj.RemoveAllListeners();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

