//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class LuaCommandWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(LuaCommand), typeof(PureMVC.Patterns.Command.SimpleCommand));
		L.RegFunction("Execute", Execute);
		L.RegFunction("OnRemove", OnRemove);
		L.RegFunction("New", _CreateLuaCommand);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("Command", get_Command, null);
		L.RegVar("CommandName", get_CommandName, null);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateLuaCommand(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 1)
			{
				string arg0 = ToLua.CheckString(L, 1);
				LuaCommand obj = new LuaCommand(arg0);
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: LuaCommand.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Execute(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			LuaCommand obj = (LuaCommand)ToLua.CheckObject<LuaCommand>(L, 1);
			PureMVC.Interfaces.INotification arg0 = (PureMVC.Interfaces.INotification)ToLua.CheckObject<PureMVC.Interfaces.INotification>(L, 2);
			obj.Execute(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnRemove(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			LuaCommand obj = (LuaCommand)ToLua.CheckObject<LuaCommand>(L, 1);
			obj.OnRemove();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Command(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			LuaCommand obj = (LuaCommand)o;
			LuaInterface.LuaTable ret = obj.Command;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index Command on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_CommandName(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			LuaCommand obj = (LuaCommand)o;
			string ret = obj.CommandName;
			LuaDLL.lua_pushstring(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index CommandName on a nil value");
		}
	}
}

