//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class LuaUIEventListenerWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(LuaUIEventListener), typeof(LuaBaseListener));
		L.RegFunction("AddEntry", AddEntry);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int AddEntry(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			LuaUIEventListener obj = (LuaUIEventListener)ToLua.CheckObject<LuaUIEventListener>(L, 1);
			UnityEngine.EventSystems.EventTriggerType arg0 = (UnityEngine.EventSystems.EventTriggerType)ToLua.CheckObject(L, 2, typeof(UnityEngine.EventSystems.EventTriggerType));
			obj.AddEntry(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

