//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class PureMVC_Patterns_Mediator_MediatorWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(PureMVC.Patterns.Mediator.Mediator), typeof(PureMVC.Patterns.Observer.Notifier));
		L.RegFunction("ListNotificationInterests", ListNotificationInterests);
		L.RegFunction("HandleNotification", HandleNotification);
		L.RegFunction("OnRegister", OnRegister);
		L.RegFunction("OnRemove", OnRemove);
		L.RegFunction("New", _CreatePureMVC_Patterns_Mediator_Mediator);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("NAME", get_NAME, set_NAME);
		L.RegVar("MediatorName", get_MediatorName, null);
		L.RegVar("ViewComponent", get_ViewComponent, set_ViewComponent);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreatePureMVC_Patterns_Mediator_Mediator(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 1)
			{
				string arg0 = ToLua.CheckString(L, 1);
				PureMVC.Patterns.Mediator.Mediator obj = new PureMVC.Patterns.Mediator.Mediator(arg0);
				ToLua.PushObject(L, obj);
				return 1;
			}
			else if (count == 2)
			{
				string arg0 = ToLua.CheckString(L, 1);
				object arg1 = ToLua.ToVarObject(L, 2);
				PureMVC.Patterns.Mediator.Mediator obj = new PureMVC.Patterns.Mediator.Mediator(arg0, arg1);
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: PureMVC.Patterns.Mediator.Mediator.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ListNotificationInterests(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			PureMVC.Patterns.Mediator.Mediator obj = (PureMVC.Patterns.Mediator.Mediator)ToLua.CheckObject<PureMVC.Patterns.Mediator.Mediator>(L, 1);
			string[] o = obj.ListNotificationInterests();
			ToLua.Push(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int HandleNotification(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			PureMVC.Patterns.Mediator.Mediator obj = (PureMVC.Patterns.Mediator.Mediator)ToLua.CheckObject<PureMVC.Patterns.Mediator.Mediator>(L, 1);
			PureMVC.Interfaces.INotification arg0 = (PureMVC.Interfaces.INotification)ToLua.CheckObject<PureMVC.Interfaces.INotification>(L, 2);
			obj.HandleNotification(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnRegister(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			PureMVC.Patterns.Mediator.Mediator obj = (PureMVC.Patterns.Mediator.Mediator)ToLua.CheckObject<PureMVC.Patterns.Mediator.Mediator>(L, 1);
			obj.OnRegister();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnRemove(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			PureMVC.Patterns.Mediator.Mediator obj = (PureMVC.Patterns.Mediator.Mediator)ToLua.CheckObject<PureMVC.Patterns.Mediator.Mediator>(L, 1);
			obj.OnRemove();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_NAME(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, PureMVC.Patterns.Mediator.Mediator.NAME);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_MediatorName(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			PureMVC.Patterns.Mediator.Mediator obj = (PureMVC.Patterns.Mediator.Mediator)o;
			string ret = obj.MediatorName;
			LuaDLL.lua_pushstring(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index MediatorName on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ViewComponent(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			PureMVC.Patterns.Mediator.Mediator obj = (PureMVC.Patterns.Mediator.Mediator)o;
			object ret = obj.ViewComponent;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index ViewComponent on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_NAME(IntPtr L)
	{
		try
		{
			string arg0 = ToLua.CheckString(L, 2);
			PureMVC.Patterns.Mediator.Mediator.NAME = arg0;
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_ViewComponent(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			PureMVC.Patterns.Mediator.Mediator obj = (PureMVC.Patterns.Mediator.Mediator)o;
			object arg0 = ToLua.ToVarObject(L, 2);
			obj.ViewComponent = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index ViewComponent on a nil value");
		}
	}
}

