//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class PureMVC_Patterns_Proxy_ProxyWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(PureMVC.Patterns.Proxy.Proxy), typeof(PureMVC.Patterns.Observer.Notifier));
		L.RegFunction("OnRegister", OnRegister);
		L.RegFunction("OnRemove", OnRemove);
		L.RegFunction("New", _CreatePureMVC_Patterns_Proxy_Proxy);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("NAME", get_NAME, null);
		L.RegVar("ProxyName", get_ProxyName, null);
		L.RegVar("Data", get_Data, set_Data);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreatePureMVC_Patterns_Proxy_Proxy(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 1)
			{
				string arg0 = ToLua.CheckString(L, 1);
				PureMVC.Patterns.Proxy.Proxy obj = new PureMVC.Patterns.Proxy.Proxy(arg0);
				ToLua.PushObject(L, obj);
				return 1;
			}
			else if (count == 2)
			{
				string arg0 = ToLua.CheckString(L, 1);
				object arg1 = ToLua.ToVarObject(L, 2);
				PureMVC.Patterns.Proxy.Proxy obj = new PureMVC.Patterns.Proxy.Proxy(arg0, arg1);
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: PureMVC.Patterns.Proxy.Proxy.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnRegister(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			PureMVC.Patterns.Proxy.Proxy obj = (PureMVC.Patterns.Proxy.Proxy)ToLua.CheckObject<PureMVC.Patterns.Proxy.Proxy>(L, 1);
			obj.OnRegister();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnRemove(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			PureMVC.Patterns.Proxy.Proxy obj = (PureMVC.Patterns.Proxy.Proxy)ToLua.CheckObject<PureMVC.Patterns.Proxy.Proxy>(L, 1);
			obj.OnRemove();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_NAME(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, PureMVC.Patterns.Proxy.Proxy.NAME);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ProxyName(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			PureMVC.Patterns.Proxy.Proxy obj = (PureMVC.Patterns.Proxy.Proxy)o;
			string ret = obj.ProxyName;
			LuaDLL.lua_pushstring(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index ProxyName on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Data(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			PureMVC.Patterns.Proxy.Proxy obj = (PureMVC.Patterns.Proxy.Proxy)o;
			object ret = obj.Data;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index Data on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_Data(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			PureMVC.Patterns.Proxy.Proxy obj = (PureMVC.Patterns.Proxy.Proxy)o;
			object arg0 = ToLua.ToVarObject(L, 2);
			obj.Data = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index Data on a nil value");
		}
	}
}

