//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class UnityEngine_EventSystems_EventTriggerTypeWrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(UnityEngine.EventSystems.EventTriggerType));
		L.RegVar("PointerEnter", get_PointerEnter, null);
		L.RegVar("PointerExit", get_PointerExit, null);
		L.RegVar("PointerDown", get_PointerDown, null);
		L.RegVar("PointerUp", get_PointerUp, null);
		L.RegVar("PointerClick", get_PointerClick, null);
		L.RegVar("Drag", get_Drag, null);
		L.RegVar("Drop", get_Drop, null);
		L.RegVar("Scroll", get_Scroll, null);
		L.RegVar("UpdateSelected", get_UpdateSelected, null);
		L.RegVar("Select", get_Select, null);
		L.RegVar("Deselect", get_Deselect, null);
		L.RegVar("Move", get_Move, null);
		L.RegVar("InitializePotentialDrag", get_InitializePotentialDrag, null);
		L.RegVar("BeginDrag", get_BeginDrag, null);
		L.RegVar("EndDrag", get_EndDrag, null);
		L.RegVar("Submit", get_Submit, null);
		L.RegVar("Cancel", get_Cancel, null);
		L.RegFunction("IntToEnum", IntToEnum);
		L.EndEnum();
		TypeTraits<UnityEngine.EventSystems.EventTriggerType>.Check = CheckType;
		StackTraits<UnityEngine.EventSystems.EventTriggerType>.Push = Push;
	}

	static void Push(IntPtr L, UnityEngine.EventSystems.EventTriggerType arg)
	{
		ToLua.Push(L, arg);
	}

	static bool CheckType(IntPtr L, int pos)
	{
		return TypeChecker.CheckEnumType(typeof(UnityEngine.EventSystems.EventTriggerType), L, pos);
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_PointerEnter(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.EventSystems.EventTriggerType.PointerEnter);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_PointerExit(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.EventSystems.EventTriggerType.PointerExit);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_PointerDown(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.EventSystems.EventTriggerType.PointerDown);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_PointerUp(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.EventSystems.EventTriggerType.PointerUp);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_PointerClick(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.EventSystems.EventTriggerType.PointerClick);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Drag(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.EventSystems.EventTriggerType.Drag);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Drop(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.EventSystems.EventTriggerType.Drop);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Scroll(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.EventSystems.EventTriggerType.Scroll);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_UpdateSelected(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.EventSystems.EventTriggerType.UpdateSelected);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Select(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.EventSystems.EventTriggerType.Select);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Deselect(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.EventSystems.EventTriggerType.Deselect);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Move(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.EventSystems.EventTriggerType.Move);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_InitializePotentialDrag(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.EventSystems.EventTriggerType.InitializePotentialDrag);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_BeginDrag(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.EventSystems.EventTriggerType.BeginDrag);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_EndDrag(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.EventSystems.EventTriggerType.EndDrag);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Submit(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.EventSystems.EventTriggerType.Submit);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Cancel(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.EventSystems.EventTriggerType.Cancel);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IntToEnum(IntPtr L)
	{
		int arg0 = (int)LuaDLL.lua_tonumber(L, 1);
		UnityEngine.EventSystems.EventTriggerType o = (UnityEngine.EventSystems.EventTriggerType)arg0;
		ToLua.Push(L, o);
		return 1;
	}
}

