//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class UnityEngine_ResourceManagement_ResourceProviders_SceneInstanceWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(UnityEngine.ResourceManagement.ResourceProviders.SceneInstance), null);
		L.RegFunction("ActivateAsync", ActivateAsync);
		L.RegFunction("GetHashCode", GetHashCode);
		L.RegFunction("Equals", Equals);
		L.RegFunction("New", _CreateUnityEngine_ResourceManagement_ResourceProviders_SceneInstance);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("Scene", get_Scene, null);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateUnityEngine_ResourceManagement_ResourceProviders_SceneInstance(IntPtr L)
	{
		UnityEngine.ResourceManagement.ResourceProviders.SceneInstance obj = new UnityEngine.ResourceManagement.ResourceProviders.SceneInstance();
		ToLua.PushValue(L, obj);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ActivateAsync(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			UnityEngine.ResourceManagement.ResourceProviders.SceneInstance obj = (UnityEngine.ResourceManagement.ResourceProviders.SceneInstance)ToLua.CheckObject(L, 1, typeof(UnityEngine.ResourceManagement.ResourceProviders.SceneInstance));
			UnityEngine.AsyncOperation o = obj.ActivateAsync();
			ToLua.PushObject(L, o);
			ToLua.SetBack(L, 1, obj);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetHashCode(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			UnityEngine.ResourceManagement.ResourceProviders.SceneInstance obj = (UnityEngine.ResourceManagement.ResourceProviders.SceneInstance)ToLua.CheckObject(L, 1, typeof(UnityEngine.ResourceManagement.ResourceProviders.SceneInstance));
			int o = obj.GetHashCode();
			LuaDLL.lua_pushinteger(L, o);
			ToLua.SetBack(L, 1, obj);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Equals(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.ResourceManagement.ResourceProviders.SceneInstance obj = (UnityEngine.ResourceManagement.ResourceProviders.SceneInstance)ToLua.CheckObject(L, 1, typeof(UnityEngine.ResourceManagement.ResourceProviders.SceneInstance));
			object arg0 = ToLua.ToVarObject(L, 2);
			bool o = obj.Equals(arg0);
			LuaDLL.lua_pushboolean(L, o);
			ToLua.SetBack(L, 1, obj);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Scene(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.ResourceManagement.ResourceProviders.SceneInstance obj = (UnityEngine.ResourceManagement.ResourceProviders.SceneInstance)o;
			UnityEngine.SceneManagement.Scene ret = obj.Scene;
			ToLua.PushValue(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index Scene on a nil value");
		}
	}
}

