//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class UnityEngine_ResourceManagement_AsyncOperations_AsyncOperationHandle_objectWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(UnityEngine.ResourceManagement.AsyncOperations.AsyncOperationHandle<object>), null, "AsyncOperationHandle_object");
		L.RegFunction("GetHashCode", GetHashCode);
		L.RegFunction("Equals", Equals);
		L.RegFunction("IsValid", IsValid);
		L.RegFunction("New", _CreateUnityEngine_ResourceManagement_AsyncOperations_AsyncOperationHandle_object);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("Task", get_Task, null);
		L.RegVar("DebugName", get_DebugName, null);
		L.RegVar("PercentComplete", get_PercentComplete, null);
		L.RegVar("Status", get_Status, null);
		L.RegVar("OperationException", get_OperationException, null);
		L.RegVar("Result", get_Result, null);
		L.RegVar("IsDone", get_IsDone, null);
		L.RegVar("Completed", get_Completed, set_Completed);
		L.RegVar("CompletedTypeless", get_CompletedTypeless, set_CompletedTypeless);
		L.RegVar("Destroyed", get_Destroyed, set_Destroyed);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateUnityEngine_ResourceManagement_AsyncOperations_AsyncOperationHandle_object(IntPtr L)
	{
		UnityEngine.ResourceManagement.AsyncOperations.AsyncOperationHandle<object> obj = new UnityEngine.ResourceManagement.AsyncOperations.AsyncOperationHandle<object>();
		ToLua.PushValue(L, obj);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetHashCode(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			UnityEngine.ResourceManagement.AsyncOperations.AsyncOperationHandle<object> obj = (UnityEngine.ResourceManagement.AsyncOperations.AsyncOperationHandle<object>)ToLua.CheckObject(L, 1, typeof(UnityEngine.ResourceManagement.AsyncOperations.AsyncOperationHandle<object>));
			int o = obj.GetHashCode();
			LuaDLL.lua_pushinteger(L, o);
			ToLua.SetBack(L, 1, obj);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Equals(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.ResourceManagement.AsyncOperations.AsyncOperationHandle<object> obj = (UnityEngine.ResourceManagement.AsyncOperations.AsyncOperationHandle<object>)ToLua.CheckObject(L, 1, typeof(UnityEngine.ResourceManagement.AsyncOperations.AsyncOperationHandle<object>));
			UnityEngine.ResourceManagement.AsyncOperations.AsyncOperationHandle<object> arg0 = StackTraits<UnityEngine.ResourceManagement.AsyncOperations.AsyncOperationHandle<object>>.Check(L, 2);
			bool o = obj.Equals(arg0);
			LuaDLL.lua_pushboolean(L, o);
			ToLua.SetBack(L, 1, obj);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IsValid(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			UnityEngine.ResourceManagement.AsyncOperations.AsyncOperationHandle<object> obj = (UnityEngine.ResourceManagement.AsyncOperations.AsyncOperationHandle<object>)ToLua.CheckObject(L, 1, typeof(UnityEngine.ResourceManagement.AsyncOperations.AsyncOperationHandle<object>));
			bool o = obj.IsValid();
			LuaDLL.lua_pushboolean(L, o);
			ToLua.SetBack(L, 1, obj);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Task(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.ResourceManagement.AsyncOperations.AsyncOperationHandle<object> obj = (UnityEngine.ResourceManagement.AsyncOperations.AsyncOperationHandle<object>)o;
			System.Threading.Tasks.Task<object> ret = obj.Task;
			ToLua.PushObject(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index Task on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_DebugName(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.ResourceManagement.AsyncOperations.AsyncOperationHandle<object> obj = (UnityEngine.ResourceManagement.AsyncOperations.AsyncOperationHandle<object>)o;
			string ret = obj.DebugName;
			LuaDLL.lua_pushstring(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index DebugName on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_PercentComplete(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.ResourceManagement.AsyncOperations.AsyncOperationHandle<object> obj = (UnityEngine.ResourceManagement.AsyncOperations.AsyncOperationHandle<object>)o;
			float ret = obj.PercentComplete;
			LuaDLL.lua_pushnumber(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index PercentComplete on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Status(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.ResourceManagement.AsyncOperations.AsyncOperationHandle<object> obj = (UnityEngine.ResourceManagement.AsyncOperations.AsyncOperationHandle<object>)o;
			UnityEngine.ResourceManagement.AsyncOperations.AsyncOperationStatus ret = obj.Status;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index Status on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_OperationException(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.ResourceManagement.AsyncOperations.AsyncOperationHandle<object> obj = (UnityEngine.ResourceManagement.AsyncOperations.AsyncOperationHandle<object>)o;
			System.Exception ret = obj.OperationException;
			ToLua.PushObject(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index OperationException on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Result(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.ResourceManagement.AsyncOperations.AsyncOperationHandle<object> obj = (UnityEngine.ResourceManagement.AsyncOperations.AsyncOperationHandle<object>)o;
			object ret = obj.Result;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index Result on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_IsDone(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.ResourceManagement.AsyncOperations.AsyncOperationHandle<object> obj = (UnityEngine.ResourceManagement.AsyncOperations.AsyncOperationHandle<object>)o;
			bool ret = obj.IsDone;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index IsDone on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Completed(IntPtr L)
	{
		ToLua.Push(L, new EventObject(typeof(System.Action<UnityEngine.ResourceManagement.AsyncOperations.AsyncOperationHandle<object>>)));
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_CompletedTypeless(IntPtr L)
	{
		ToLua.Push(L, new EventObject(typeof(System.Action<UnityEngine.ResourceManagement.AsyncOperations.AsyncOperationHandle>)));
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Destroyed(IntPtr L)
	{
		ToLua.Push(L, new EventObject(typeof(System.Action<UnityEngine.ResourceManagement.AsyncOperations.AsyncOperationHandle>)));
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_Completed(IntPtr L)
	{
		try
		{
			UnityEngine.ResourceManagement.AsyncOperations.AsyncOperationHandle<object> obj = (UnityEngine.ResourceManagement.AsyncOperations.AsyncOperationHandle<object>)ToLua.CheckObject(L, 1, typeof(UnityEngine.ResourceManagement.AsyncOperations.AsyncOperationHandle<object>));
			EventObject arg0 = null;

			if (LuaDLL.lua_isuserdata(L, 2) != 0)
			{
				arg0 = (EventObject)ToLua.ToObject(L, 2);
			}
			else
			{
				return LuaDLL.luaL_throw(L, "The event 'UnityEngine.ResourceManagement.AsyncOperations.AsyncOperationHandle<object>.Completed' can only appear on the left hand side of += or -= when used outside of the type 'UnityEngine.ResourceManagement.AsyncOperations.AsyncOperationHandle<object>'");
			}

			if (arg0.op == EventOp.Add)
			{
				System.Action<UnityEngine.ResourceManagement.AsyncOperations.AsyncOperationHandle<object>> ev = (System.Action<UnityEngine.ResourceManagement.AsyncOperations.AsyncOperationHandle<object>>)arg0.func;
				obj.Completed += ev;
			}
			else if (arg0.op == EventOp.Sub)
			{
				System.Action<UnityEngine.ResourceManagement.AsyncOperations.AsyncOperationHandle<object>> ev = (System.Action<UnityEngine.ResourceManagement.AsyncOperations.AsyncOperationHandle<object>>)arg0.func;
				obj.Completed -= ev;
			}

			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_CompletedTypeless(IntPtr L)
	{
		try
		{
			UnityEngine.ResourceManagement.AsyncOperations.AsyncOperationHandle<object> obj = (UnityEngine.ResourceManagement.AsyncOperations.AsyncOperationHandle<object>)ToLua.CheckObject(L, 1, typeof(UnityEngine.ResourceManagement.AsyncOperations.AsyncOperationHandle<object>));
			EventObject arg0 = null;

			if (LuaDLL.lua_isuserdata(L, 2) != 0)
			{
				arg0 = (EventObject)ToLua.ToObject(L, 2);
			}
			else
			{
				return LuaDLL.luaL_throw(L, "The event 'UnityEngine.ResourceManagement.AsyncOperations.AsyncOperationHandle<object>.CompletedTypeless' can only appear on the left hand side of += or -= when used outside of the type 'UnityEngine.ResourceManagement.AsyncOperations.AsyncOperationHandle<object>'");
			}

			if (arg0.op == EventOp.Add)
			{
				System.Action<UnityEngine.ResourceManagement.AsyncOperations.AsyncOperationHandle> ev = (System.Action<UnityEngine.ResourceManagement.AsyncOperations.AsyncOperationHandle>)arg0.func;
				obj.CompletedTypeless += ev;
			}
			else if (arg0.op == EventOp.Sub)
			{
				System.Action<UnityEngine.ResourceManagement.AsyncOperations.AsyncOperationHandle> ev = (System.Action<UnityEngine.ResourceManagement.AsyncOperations.AsyncOperationHandle>)arg0.func;
				obj.CompletedTypeless -= ev;
			}

			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_Destroyed(IntPtr L)
	{
		try
		{
			UnityEngine.ResourceManagement.AsyncOperations.AsyncOperationHandle<object> obj = (UnityEngine.ResourceManagement.AsyncOperations.AsyncOperationHandle<object>)ToLua.CheckObject(L, 1, typeof(UnityEngine.ResourceManagement.AsyncOperations.AsyncOperationHandle<object>));
			EventObject arg0 = null;

			if (LuaDLL.lua_isuserdata(L, 2) != 0)
			{
				arg0 = (EventObject)ToLua.ToObject(L, 2);
			}
			else
			{
				return LuaDLL.luaL_throw(L, "The event 'UnityEngine.ResourceManagement.AsyncOperations.AsyncOperationHandle<object>.Destroyed' can only appear on the left hand side of += or -= when used outside of the type 'UnityEngine.ResourceManagement.AsyncOperations.AsyncOperationHandle<object>'");
			}

			if (arg0.op == EventOp.Add)
			{
				System.Action<UnityEngine.ResourceManagement.AsyncOperations.AsyncOperationHandle> ev = (System.Action<UnityEngine.ResourceManagement.AsyncOperations.AsyncOperationHandle>)arg0.func;
				obj.Destroyed += ev;
			}
			else if (arg0.op == EventOp.Sub)
			{
				System.Action<UnityEngine.ResourceManagement.AsyncOperations.AsyncOperationHandle> ev = (System.Action<UnityEngine.ResourceManagement.AsyncOperations.AsyncOperationHandle>)arg0.func;
				obj.Destroyed -= ev;
			}

			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

